services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_backend_container
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:1234567890@db:5432/taskdb
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:18
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_USER=postgres
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
